import { build } from "esbuild";
import { mkdir, writeFile } from "node:fs/promises";

async function bundle(entryPoint, exportName) {
  const result = await build({
    entryPoints: [entryPoint],
    bundle: true,
    format: "iife",
    platform: "browser",
    target: ["es2022"],
    minify: true,
    write: false,
    legalComments: "none",
  });

  const javascript = result.outputFiles[0]?.text;
  if (!javascript) {
    throw new Error(`${exportName} browser bundle was not generated.`);
  }
  return javascript;
}

const [routesBundle, walletBundle, siteNavBundle, guardBuilderWalletBundle] =
  await Promise.all([
    bundle("src/browser/routes.ts", "routes"),
    bundle("src/browser/wallet.ts", "wallet"),
    bundle("src/browser/site-nav.ts", "site-nav"),
    bundle("src/browser/guard-builder-wallet.ts", "guard-builder-wallet"),
  ]);

await mkdir("src/generated", { recursive: true });

const header =
  "// Generated by scripts/build-browser.mjs. Do not edit by hand.\n";

await Promise.all([
  writeFile(
    "src/generated/routes-bundle.ts",
    `${header}export const routesBundle = ${JSON.stringify(routesBundle)};\n`,
    "utf8",
  ),
  writeFile(
    "src/generated/wallet-bundle.ts",
    `${header}export const walletBundle = ${JSON.stringify(walletBundle)};\n`,
    "utf8",
  ),
  writeFile(
    "src/generated/site-nav-bundle.ts",
    `${header}export const siteNavBundle = ${JSON.stringify(siteNavBundle)};\n`,
    "utf8",
  ),
  writeFile(
    "src/generated/guard-builder-wallet-bundle.ts",
    `${header}export const guardBuilderWalletBundle = ${JSON.stringify(guardBuilderWalletBundle)};\n`,
    "utf8",
  ),
]);
