import { build } from "esbuild";
import { mkdir, writeFile } from "node:fs/promises";

const result = await build({
  entryPoints: ["src/browser/routes.ts"],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: ["es2022"],
  minify: true,
  write: false,
  legalComments: "none",
});

const javascript = result.outputFiles[0]?.text;
if (!javascript) throw new Error("Routes browser bundle was not generated.");

await mkdir("src/generated", { recursive: true });
await writeFile(
  "src/generated/routes-bundle.ts",
  `// Generated by scripts/build-browser.mjs. Do not edit by hand.\nexport const routesBundle = ${JSON.stringify(javascript)};\n`,
  "utf8",
);
